### PR TITLE
chore: remove unnecessary warnings of deprecated

### PR DESCRIPTION
**Pull request by unix**
## PR Checklist

- [x] Fix linting errors
- [x] Label has been added

### CODE REVIEW

**Comment by c0b41** [comment]
So breaking change coming?

**Comment by unix** [comment]
@c0b41 
Yes. v1.5+ contains some breaking changes: [pre-release](https://github.com/zeit-ui/react/releases/tag/v1.5.0-rc.0). Mainly the renaming of 2 modules. 

The name of the module is changed to better conform to the naming specification, and [for better support tree-shaking](https://github.com/zeit-ui/react/blob/rc/examples/tree-shaking-create-react-app/README.md).  (there is no change in component behavior.)

**Comment by unix** [comment]
Update:
The size shown in the [example](https://github.com/zeit-ui/react/blob/rc/examples/tree-shaking-create-react-app/README.md) is unzipped. The current size of the full package after gzip is about [48.6kb](https://cdn.jsdelivr.net/npm/@zeit-ui/react@1.5.0-rc.1/dist/index.min.js), if you use `tree-shaking`, the package will be smaller.

**Comment by c0b41** [comment]
@unix yeah, i see that, thnx for smaller bundle ❤❤

**Pull request merged**
