### PR TITLE
fix: fixed typo

### PR DESCRIPTION
**Pull request by Norviah**
# PR Checklist

- [ ] Fix linting errors
- [ ] Label has been added

# Change information

Fixed a typo, changed "warpper" to "wrapper"

### CODE REVIEW

**Comment by unix** [comment]
Thanks.
Can we optimize `commit message`? refer to [contributing doc](https://github.com/zeit-ui/react/blob/master/.github/CONTRIBUTING.md).

**Comment by Norviah** [comment]
Apologies, fixed.

**Comment by unix** [comment]
Please refer to the message style guide [here](https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/README.md), and useless commit history needs to be removed.

**Comment by Norviah** [comment]
I think I updated to the correct format, but, I have no idea on how to delete a commit (and me deleting the original repo definitely did not help - you live n learn). I made a new pull request [here](https://github.com/zeit-ui/react/pull/185).

**Pull request closed without merging**
