### PR TITLE
fix(input): always synchronize external value and ignore changes

### LINKED ISSUE #335: Input value can't be simply controlled by `value` prop
# Bug report 🐞
Not sure if this is a bug or a design decision. In the scanbox link, keep input in either input, you can see the <input>'s value is controlled by the `value` state while the <Input> is not.

## Version & Environment

  - Version of browser chrome Version 83.0.4103.116 (Official Build) (64-bit)
  - Version of `zeit-ui/react` check sandbox

## Expection

Just want to know if this is intentional.

### PR DESCRIPTION
**Pull request by unix**
## Checklist

- [x] Fix linting errors
- [x] Tests have been added / updated (or snapshots)

## Change information

Fixed #335

### CODE REVIEW

**Comment by yqrashawn** [comment]
this will broke clear feature if there's `value` prop

**Comment by unix** [comment]
> this will broke clear feature if there's `value` prop

Yup, if you want to use *clear*, you need to synchronize manually: (or not using `value`)

```jsx
const [val, setVal] = useState('')
<Input value={val} onChange={e => setVal(e.target.value)} />
```

**Comment by yqrashawn** [comment]
Maybe show users an error when both `value` and `clearable` are used?

**Comment by unix** [comment]
> Maybe show users an error when both value and clearable are used?

In fact, there is no error in the use `value` and `clearable` at the same time, I will not pay for the wrong use of the user.  (If you follow your code always, `antd` will also not work.)

**Comment by yqrashawn** [comment]
That's fair enough.

**Pull request merged**
